/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package java_code;

import org.junit.Test;
import static org.junit.Assert.*;

public class LibraryTest {
    @Test public void testShouldPass() {
        Library classUnderTest = new Library();
        assertEquals("someLibraryMethod should return '2'", classUnderTest.add(1,1), 2);
    }
    @Test public void testShouldFail() {
        Library classUnderTest = new Library();
        assertEquals("someLibraryMethod should not return '3'", classUnderTest.add(1,1), 3);
    }
}
